const PatitentType = {
    ADD_PATITENT: 'ADD_PATITENT',
    ADD_PATITENT_SUCCESS: 'ADD_PATITENT_SUCCESS',
    ADD_PATITENT_FAILURE: 'ADD_PATITENT_FAILURE',

    GET_PATITENT: 'GET_PATITENT',
    GET_PATITENT_SUCCESS: 'GET_PATITENT_SUCCESS',
    GET_PATITENT_FAILURE: 'GET_PATITENT_FAILURE',

    GET_PATITENTS: 'GET_PATITENTS',
    GET_PATITENTS_SUCCESS: 'GET_PATITENTS_SUCCESS',
    GET_PATITENTS_FAILURE: 'GET_PATITENTS_FAILURE',
}

const MedicineType = {
    GET_MEDICINE: 'GET_MEDICINEATITENTS',
    GET_MEDICINE_SUCCESS: 'GET_MEDICINE_SUCCESS',
    GET_MEDICINE_FAILURE: 'GET_MEDICINE_FAILURE',
}

const UserType = {
    GET_USER: 'GET_USER',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURD',

    GET_USERS: 'GET_USERS',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURD: 'GET_USERS_FAILURD',
}

const ResultType = {
    GET_RESULT: 'GET_RESULT',
    GET_RESULT_SUCCESS: 'GET_RESULT_SUCCESS',
    GET_RESULT_FAILURE: 'GET_RESULT_FAILURE',

    GET_RESULTS: 'GET_RESULTS',
    GET_RESULTS_SUCCESS: 'GET_RESULTS_SUCCESS',
    GET_RESULTS_FAILURE: 'GET_RESULTS_FAILURE',    
}

const UnsuitableType = {
    GET_SAMPLE: 'GET_SAMPLE',
    GET_SAMPLE_SUCCESS: 'GET_SAMPLE_SUCCESS',
    GET_SAMPLE_FAILURE: 'GET_SAMPLE_FAILURE',

    GET_SAMPLES: 'GET_SAMPLES',
    GET_SAMPLES_SUCCESS: 'GET_SAMPLES_SUCCESS',
    GET_SAMPLES_FAILURE: 'GET_SAMPLES_FAILURE',
}


const Types = {
    ...PatitentType,
    ...MedicineType,
    ...UserType,
    ...ResultType,
    ...UnsuitableType
}

export default Types;